### ISSUE TITLE
Optional configs not optional

### ISSUE THREAD

**Issue by thoppa** [jseidl/hass-magic_areas#236] opened 2022-07-17 04:08 UTC
**Describe the bug**

Every field is required.  I can’t leave anything empty: excluded entities, sleep entities, etc.  it errors with

User input malformed: expected str for dictionary value @ data['sleep_entity']

or whatever field is blank

**To Reproduce**

attempt to “configure” area.  Leave “excluded entities” blank.

**Expected behavior**

all optional features should be optional

**Comment by jseidl** [comment] 2022-07-17 05:11
I can confirm this. Something weird with the new selectors, working on it.

**Comment by jseidl** [comment] 2022-07-17 07:11
Just pushed PR #237 which should fix it. Will be testing for the next week. @thoppa if you'd like to test early, pull the `config_flow.py` code from [hotfix/config-flow-selectors-optional](https://github.com/jseidl/hass-magic_areas/tree/hotfix/config-flow-selectors-optional) branch. Otherwise I shall be releasing the hotfix next week.

**Comment by mbbush** [comment] 2022-07-20 18:23
This was caused by something in the upgrade from home assistant 2017.7.4 to 2017.7.5

**Comment by jseidl** [comment] 2022-07-21 03:45
@mbbush thanks for the heads up! New release of MA has the fixes for this issue, closing!

**Closed by jseidl** 2022-07-21 03:45 UTC
Labels: bug
