### ISSUE TITLE
Feature Request: Add dark attribute to binary_sensor.area_<area_name>

### ISSUE THREAD

**Issue by klatka** [jseidl/hass-magic_areas#106] opened 2021-03-10 17:53 UTC
It would be a nice feature to have an additional attribute in the binary_sensor.area_<area_name> called dark.

My idea is to configure a threshold in lx in the config of the area to determine whether the area is dark or not.
So if I set a threshold of 10 lx and there is an illuminance sensor assigned to this area which measures the value of 5 lx the attribute dark is set to true, else false.

As consequence, the automatic lights feature would only turn on the lights if the area is dark.
For users who don't use the automatic lights feature it would be easier to determine when to turn on the lights for this area in their automation.  And there would be a central place to set this threshold.

If there is any illuminance sensor assigned into this area we could use the lights to determine the dark attribute.

Please tell me what do you think about it.
Thank you!

**Comment by TheArcturian** [comment] 2021-03-10 18:25
I definitively agree on the suggestion. I have a lot of rooms where each room needs a different value for the lx to turn on the lights optimally. This would solve it perfectly.

Alternatively they need to be created manually and maintained in a .yaml file, but it would be great to have it as an integrated part of the awesome Magic Areas.

**Comment by jseidl** [comment] 2021-03-27 23:47
That's a good feature indeed, added to the work log

**Comment by jseidl** [comment] 2021-10-19 03:59
Just realized this is a duplicate of #30, which means I got this feature request a LOT so I should probably work on that next after `3.0.0` release.

@caphm had manifested interest in working on that one. Let me know if you have the time, if not I can take a stab at it. I still have to port the cool stuff from #101 into `3.0.0` tho

**Closed by jseidl** 2021-10-19 03:59 UTC
Labels: duplicate, feature-request
