### ISSUE TITLE
HA 2023.1.0 | Error during setup of component magic_areas

### ISSUE THREAD

**Issue by johnjoemorgan** [jseidl/hass-magic_areas#270] opened 2023-01-05 07:29 UTC
Supervisor 2022.12.1
Operating System 9.4 
Frontend 20230104.0 - latest 

After install of latest 2023.1.0 HA version, an error is logged on start-up

`
Logger: homeassistant.setup
Source: custom_components/magic_areas/__init__.py:67
Integration: magic_areas ([documentation](https://github.com/jseidl/hass-magic_areas/wiki), [issues](https://github.com/jseidl/hass-magic_areas/issues))
First occurred: 14:41:26 (1 occurrences)
Last logged: 14:41:26
Error during setup of component magic_areas

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/magic_areas/__init__.py", line 67, in async_setup
    AreaEntry(
TypeError: AreaEntry.__init__() missing 1 required positional argument: 'aliases'
`

**Comment by pservais** [comment] 2023-01-05 07:34
Same error here.

**Comment by pservais** [comment] 2023-01-05 08:03
Temporary fixed by adding `, aliases=meta_area.lower()` to line 68 in init.py
Probably not the correct solution, but Magic Areas starts correctly with this fix

**Comment by hyperfive** [comment] 2023-01-07 14:11
> Temporary fixed by adding `, aliases=meta_area.lower()` to line 68 in init.py
> Probably not the correct solution, but Magic Areas starts correctly with this fix

This worked for me.  Thank you! has someone done a PR on this change?

**Comment by jseidl** [comment] 2023-01-07 19:55
Duplicate of #265, will track there

**Closed by jseidl** 2023-01-07 19:55 UTC

**Comment by thoppa** [comment] 2023-01-09 06:35
This needs to make min version 2023.1. Prior versions aren’t fixed
