### ISSUE TITLE
binary_sensor with customize device_class fails

### ISSUE THREAD

**Issue by geckom** [jseidl/hass-magic_areas#66] opened 2020-12-17 23:34 UTC
I have a number of Multisensor 6 zwave devices. These load into homeassistant as a binary_sensor for motion detection but have a None type for device_class.

While I have added in a customize entry to add a device_class of motion to these devices, it appears magic_ares does not pick this up. 

Some simple debugging of the script shows that device_class=None in the codebase, but on the UI it shows as a motion class. I suspect that the code is loading the device information without taking into consideration customize entries.

Is there a solution to this problem or can it be patched in the code?

**Comment by jseidl** [comment] 2020-12-28 09:13
This is indeed something that is currently unsupported as Magic Areas depends on `device_class` and looks like customizations are done after the plugin has loaded. I'm working on how to address me as this affects some ESPHome-based sensors as well.

**Comment by thoughtleader** [comment] 2020-12-29 02:35
I've totally ran into the customizations issue; do light entities need to be "devices" to be picked up magic areas. I've had a lot of luck in about half of my house, where I have actual lights, but then as we move to the garage or to some of the more creative spaces in the house, where lighting is controlled by switchable outlets, things start to get much less reliable. I'm posting here because geckom's comment totally addressed part of my troubleshooting..and along the way I've noticed that any effort to modify entities like switches, so they appear as lights (via light switch > light group) never seems to do the trick. By trick I mean, upon restarting, the area still doesn't not list the lights). 

I've just started sifting through your code to understand init order, but do you think this is a problem caused by something similar to entities I've customized, where switches are becoming lights  after magic areas inits....or is there something I'm missing in terms of when things change post initial init.

**Comment by jseidl** [comment] 2021-01-06 07:20
It could be part of this "race condition". I have some sensors that *sometimes* loads into the area and sometimes it doesn't which makes me think there's a race condition between MA loading and the entities loading. Still not 100% sure on how to address it. One idea is to only actually init MA when HA fully loads but that can have other complications. I'm doing a bunch of testing and hope to have a solution soon.

Meanwhile, @thoughtleader, have you tried using [Template Light](https://www.home-assistant.io/integrations/light.template/) entities?

**Comment by TheArcturian** [comment] 2021-01-18 23:00
I have the same issue with Aeotec Recessed Door Sensor Gen5. It is missing the device_class so I added it in configuration.yaml. I can confirm it works fine in Developer Tools, but still no door sensor in the Area it belongs.

`homeassistant:
  customize_glob:
    binary_sensor.dor_maldek_sensor:
      device_class: door`

**Comment by jseidl** [comment] 2021-01-23 08:11
Finally got to the bottom of this and there's a PR coming to fix all of our `customize` issues! See PR #74 for more information. I'll be merging into the `develop` branch during the weekend along with #71 which I'll be testing on my production stack in preparation for release 2.0.0.

**Comment by TheArcturian** [comment] 2021-01-23 11:37
Brilliant! Really looking forward to your 2.0 release!

**Comment by jseidl** [comment] 2021-01-31 08:31
Closed by #74, released on [2.0.0](https://github.com/jseidl/hass-magic_areas/releases/tag/v2.0.0).

**Closed by jseidl** 2021-01-31 08:31 UTC
Labels: bug
