### ISSUE TITLE
Feature Request: Flag for turning of sensor creation

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#25] opened 2020-10-20 17:37 UTC
After the initialization the component creates a lot of sensors. Sometimes it doesn't make that much sense. E.g. I have a room with only 1 window. I don't need a aggregated sensor. MaYbe it's good practice to implement a flag to deactivate the sensor creation or implement a feature that a sensor is only created if a minimum of two components was assigned.

**Comment by jseidl** [comment] 2020-10-20 18:53
Duplicate of #2

**Closed by jseidl** 2020-10-20 18:53 UTC
Labels: feature-request
